blank_issues_enabled: false
# contact_links:
#  - name: "Help"
#    url: "https://help.github.com"
#    about: "Get help with using this template"
#  - name: "GitHub Docs"
#    url: "https://docs.github.com"
#    about: "Learn more about GitHub features"
#  - name: "GitHub Community Forum"
#    url: "https://github.community"
#    about: "Ask questions, find answers, and connect with the GitHub Community"
